### ISSUE TITLE
Different results on arm64 with LAPACKE_dgeev

### ISSUE THREAD

**Issue by siddhesh** [Reference-LAPACK/lapack#374] opened 2019-11-29 07:08 UTC
The following reproducer was adapted from an example in [Intel mkl_lapack](https://software.intel.com/sites/products/documentation/doclib/mkl_sa/11/mkl_lapack_examples/lapacke_dgeev_col.c.htm) documentation.  If you do not have access to an arm64 system, you can request on from the [GCC compile farm](https://gcc.gnu.org/wiki/CompileFarm).  If that doesn't work, I'll be happy to help set up an account on my test box over email.

I tried to dig around to see if there were any obvious issues such as undefined behaviour causing this, but I couldn't pinpoint any.  I found significant rounding variations in intermediate results as I stepped through the code on x86 and arm64, but I couldn't get much further than that.

The reproducer gives the following output on x86, when built with `-mtune=native` on a coffee lake CPU:

```
LAPACKE_dgeev (column-major, high-level) Example Program Results

 Eigenvalues
      12.00 (      1.00,      5.00) (      1.00,     -5.00)       2.00

 Left eigenvectors
       0.50 (     -0.50,      0.00) (     -0.50,     -0.00)       0.50
      -0.50 (     -0.00,      0.50) (     -0.00,     -0.50)       0.50
       0.50 (     -0.00,      0.50) (     -0.00,     -0.50)      -0.50
       0.50 (      0.50,      0.00) (      0.50,     -0.00)       0.50

 Right eigenvectors
       0.50 (      0.00,      0.50) (      0.00,     -0.50)       0.50
      -0.50 (      0.50,      0.00) (      0.50,     -0.00)       0.50
       0.50 (      0.50,      0.00) (      0.50,     -0.00)      -0.50
       0.50 (     -0.00,     -0.50) (     -0.00,      0.50)       0.50
```

The same example however when built and run on arm64, gives the following output:

```
LAPACKE_dgeev (column-major, high-level) Example Program Results

 Eigenvalues
      12.00 (      1.00,      5.00) (      1.00,     -5.00)       2.00

 Left eigenvectors
       0.50 (      0.50,      0.00) (      0.50,     -0.00)       0.50
      -0.50 (      0.00,     -0.50) (      0.00,      0.50)       0.50
       0.50 (     -0.00,     -0.50) (     -0.00,      0.50)      -0.50
       0.50 (     -0.50,      0.00) (     -0.50,     -0.00)       0.50

 Right eigenvectors
       0.50 (     -0.50,      0.00) (     -0.50,     -0.00)       0.50
      -0.50 (     -0.00,      0.50) (     -0.00,     -0.50)       0.50
       0.50 (     -0.00,      0.50) (     -0.00,     -0.50)      -0.50
       0.50 (      0.50,     -0.00) (      0.50,      0.00)       0.50
```
The reproducer:
```c
#include <stdlib.h>
#include <stdio.h>
#include <lapacke.h>

/* Auxiliary routines prototypes */
extern void print_eigenvalues (char *desc, int n, double *wr, double *wi);
extern void print_eigenvectors (char *desc, int n, double *wi, double *v,
				int ldv);

/* Parameters */
//#define N 5
#define N 4
#define LDA N
#define LDVL N
#define LDVR N

/* Main program */
int
main ()
{
  /* Locals */
  int n = N, lda = LDA, ldvl = LDVL, ldvr = LDVR, info = 1;
  /* Local arrays */
  double wr[N], wi[N], vl[LDVL * N], vr[LDVR * N];
  double a[LDA * N] = {
    +4.0, +0.0, +5.0, 3.0,
    -5.0, +4.0, -3.0, 0.0,
    +0.0, -3.0, +4.0, 5.0,
    +3.0, -5.0, +0.0, 4.0,
  };
  /* Executable statements */
  printf
    ("LAPACKE_dgeev (column-major, high-level) Example Program Results\n");
  /* Solve eigenproblem */
  info = LAPACKE_dgeev (LAPACK_COL_MAJOR, 'V', 'V', n, a, lda, wr, wi, vl, ldvl, vr, ldvr);
  /* Check for convergence */
  if (info > 0)
    {
      printf ("The algorithm failed to compute eigenvalues.\n");
      exit (1);
    }
  /* Print eigenvalues */
  print_eigenvalues ("Eigenvalues", n, wr, wi);
  /* Print left eigenvectors */
  print_eigenvectors ("Left eigenvectors", n, wi, vl, ldvl);
  /* Print right eigenvectors */
  print_eigenvectors ("Right eigenvectors", n, wi, vr, ldvr);
  exit (0);
}				/* End of LAPACKE_dgeev Example */

/* Auxiliary routine: printing eigenvalues */
void
print_eigenvalues (char *desc, int n, double *wr, double *wi)
{
  int j;
  printf ("\n %s\n", desc);

  for (j = 0; j < n; j++)
    {
      if (wi[j] == (double) 0.0)
	{
	  printf (" %10.2f", wr[j]);
	}
      else
	{
	  printf (" (%10.2f,%10.2f)", wr[j], wi[j]);
	}
    }
  printf ("\n");
}

/* Auxiliary routine: printing eigenvectors */
void
print_eigenvectors (char *desc, int n, double *wi, double *v, int ldv)
{
  int i, j;
  printf ("\n %s\n", desc);
  for (i = 0; i < n; i++)
    {
      j = 0;
      while (j < n)
	{
	  if (wi[j] == (double) 0.0)
	    {
	      printf (" %10.2f", v[i + j * ldv]);
	      j++;
	    }
	  else
	    {
	      printf (" (%10.2f,%10.2f)", v[i + j * ldv], v[i + (j + 1) * ldv]);
	      printf (" (%10.2f,%10.2f)", v[i + j * ldv],
		      -v[i + (j + 1) * ldv]);
	      j += 2;
	    }
	}
      printf ("\n");
    }
}
```

**Comment by langou** [comment] 2019-11-29 14:43
(quickly) For the right eigenvectors, can you check whether || A*V(:,i) - V(:,i)* D(i,i) || is ``small``? 
Julien. (You can take any vector norm. For example the max-norm.)

**Comment by langou** [comment] 2019-11-30 04:13
If you look at your output for 2nd right eigenvector on x86, (for example,) you have:
w_x86 = [ 0.5*i ; 0.5; 0.5; -0.5*i ]
If you look at your output for 2nd right eigenvector on arm, you have:
w_arm = [ -0.5 ; 0.5*i; 0.5*i; 0.5 ]
These two eigenvectors look different but they are the same. Indeed
w_arm = i * w_x86

Remember that eigenvectors are known up to a multiplicative constant.

Since LAPACK normalize eigenvectors so that they have a unit norm: (real) in the real case, eigenvectors are the same up to a sign; (complex) in the complex case, eigenvectors are the same up to a e^(i*theta) (a complex number of modulus 1).

Given different implementations, with various arithmetic (arm64 or x86), one might return w and the other w * ( e^( i * pi/3 ) ) for example. It is not apparent that both answers are the same; using our eyes, they look widely different. Both answers are correct. Neither is better than the other. We cannot expect reproducible execution. That being said we should expect that || A * v - v * lambda || is small.

**Comment by langou** [comment] 2019-11-30 04:42
Not very proud of me. I wrote a quick code to check right eigenvectors. Please have a look. Seems to work on my machine.  The check for a complex eigencouple and its complex-conjugate associate eigencouple is the same, so I repeated twice the computation. 

`
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <lapacke.h>

/* Auxiliary routines prototypes */
extern void print_eigenvalues (char *desc, int n, double *wr, double *wi);
extern void print_eigenvectors (char *desc, int n, double *wi, double *v,
				int ldv);
extern void check_right ( int n, double *a, int lda, double *wr, double *wi, double *v, int ldv);


/* Parameters */
//#define N 5
#define N 4
#define LDA N
#define LDVL N
#define LDVR N

/* Main program */
int
main ()
{
  /* Locals */
  int n = N, lda = LDA, ldvl = LDVL, ldvr = LDVR, info = 1;
  /* Local arrays */
  double wr[N], wi[N], vl[LDVL * N], vr[LDVR * N];
  double a[LDA * N] = {
    +4.0, +0.0, +5.0, 3.0,
    -5.0, +4.0, -3.0, 0.0,
    +0.0, -3.0, +4.0, 5.0,
    +3.0, -5.0, +0.0, 4.0,
  };
  /* Executable statements */
  printf
    ("LAPACKE_dgeev (column-major, high-level) Example Program Results\n");
  /* Solve eigenproblem */
  info = LAPACKE_dgeev (LAPACK_COL_MAJOR, 'V', 'V', n, a, lda, wr, wi, vl, ldvl, vr, ldvr);
  /* restore A */
  a[ 0] =  +4.0; a[ 1] = +0.0; a[ 2] = +5.0; a[ 3] = 3.0;
  a[ 4] =  -5.0; a[ 5] = +4.0; a[ 6] = -3.0; a[ 7] = 0.0;
  a[ 8] =  +0.0; a[ 9] = -3.0; a[10] = +4.0; a[11] = 5.0;
  a[12] =  +3.0; a[13] = -5.0; a[14] = +0.0; a[15] = 4.0;

  /* Check for convergence */
  if (info > 0)
    {
      printf ("The algorithm failed to compute eigenvalues.\n");
      exit (1);
    }
  /* Print eigenvalues */
  print_eigenvalues ("Eigenvalues", n, wr, wi);
  /* Print left eigenvectors */
  print_eigenvectors ("Left eigenvectors", n, wi, vl, ldvl);
  /* Print right eigenvectors */
  print_eigenvectors ("Right eigenvectors", n, wi, vr, ldvr);

  check_right( n, a, lda, wr, wi, vr, ldvr );

  exit (0);
}				/* End of LAPACKE_dgeev Example */

void
check_right ( int n, double *a, int lda, double *wr, double *wi, double *v, int ldv)
{
  int i, j, k;
  double tmp, norm;

  for (k = 0; k < n; k++)
    {
      if (wi[k] == (double) 0.0)
	{
        printf (" %d ", k );

          norm = 0.0e+00;
          for (i = 0; i < n; i++){
            tmp = v[i + k * ldv] * wr[k];
            for (j = 0; j < n; j++){
               tmp -= a[i + j * lda] * v[j + k * ldv] ;
            }
            norm += tmp*tmp ;
          }

        printf (" %e \n",sqrt(norm) );

	}
      else
	{

        printf (" %d ", k );

          norm = 0.0e+00;
          for (i = 0; i < n; i++){
            tmp = v[i + k * ldv] * wr[k] - v[i + (k+1) * ldv] * wi[k];
            for (j = 0; j < n; j++){
               tmp -= a[i + j * lda] * v[j + k * ldv] ;
            }
            norm += tmp*tmp ;
          }

          for (i = 0; i < n; i++){
            tmp = v[i + k * ldv] * wi[k] + v[i + (k+1) * ldv] * wr[k];
            for (j = 0; j < n; j++){
               tmp -= a[i + j * lda] * v[j + (k+1) * ldv] ;
            }
            norm += tmp*tmp ;
          }

        printf (" %e \n",sqrt(norm) );

        printf (" %d ", k+1 );

          norm = 0.0e+00;
          for (i = 0; i < n; i++){
            tmp = v[i + k * ldv] * wr[k] - v[i + (k+1) * ldv] * wi[k];
            for (j = 0; j < n; j++){
               tmp -= a[i + j * lda] * v[j + k * ldv] ;
            }
            norm += tmp*tmp ;
          }

          for (i = 0; i < n; i++){
            tmp = v[i + k * ldv] * wi[k] + v[i + (k+1) * ldv] * wr[k];
            for (j = 0; j < n; j++){
               tmp -= a[i + j * lda] * v[j + (k+1) * ldv] ;
            }
            norm += tmp*tmp ;
          }

        printf (" %e \n",sqrt(norm) );

        k++;

	}
    }
}




/* Auxiliary routine: printing eigenvalues */
void
print_eigenvalues (char *desc, int n, double *wr, double *wi)
{
  int j;
  printf ("\n %s\n", desc);

  for (j = 0; j < n; j++)
    {
      if (wi[j] == (double) 0.0)
	{
	  printf (" %10.2f", wr[j]);
	}
      else
	{
	  printf (" (%10.2f,%10.2f)", wr[j], wi[j]);
	}
    }
  printf ("\n");
}

/* Auxiliary routine: printing eigenvectors */
void
print_eigenvectors (char *desc, int n, double *wi, double *v, int ldv)
{
  int i, j;
  printf ("\n %s\n", desc);
  for (i = 0; i < n; i++)
    {
      j = 0;
      while (j < n)
	{
	  if (wi[j] == (double) 0.0)
	    {
	      printf (" %10.2f", v[i + j * ldv]);
	      j++;
	    }
	  else
	    {
	      printf (" (%10.2f,%10.2f)", v[i + j * ldv], v[i + (j + 1) * ldv]);
	      printf (" (%10.2f,%10.2f)", v[i + j * ldv],
		      -v[i + (j + 1) * ldv]);
	      j += 2;
	    }
	}
      printf ("\n");
    }
}
`

**Comment by siddhesh** [comment] 2019-12-02 13:46
Thank you for the detailed explanation.  Apoligies it took me long to verify; I had to take some time to digest the explanation :)

That said, indeed the delta is of the order of `e-15` on arm64 too, so I reckon this is not a bug.

**Comment by langou** [comment] 2019-12-02 20:37
Sounds good. The subroutine ``check_right`` was written very quickly so I am not sure how much correct it is, corner cases, etc. Also it would be good to write ``check_left``. Also, another problem is that if a bugged subroutine would return n times the same eigencouple, the routine ``check_right`` would return 1e-15. Also, I did not do any normalization whatsoever in the checks. I am closing the issue for now. Thanks for asking the question. Cheers, Julien.

**Closed by langou** 2019-12-02 20:37 UTC
