### ISSUE TITLE
Increased number of test failures in CI

### ISSUE THREAD

**Issue by angsch** [Reference-LAPACK/lapack#695] opened 2022-08-02 18:38 UTC
HEAD has an increased number of numerical failures compared to ca. 1/2 year ago. Note that the errors do not make CI mark the run as failed.

Now it is 
```
 		Processing LAPACK Testing output found in the TESTING directory
SUMMARY             	nb test run 	numerical error   	other error  
================   	===========	=================	================  
REAL             	1317267		12	(0.001%)	0	(0.000%)	
DOUBLE PRECISION	1318089		39	(0.003%)	0	(0.000%)	
COMPLEX          	777619		0	(0.000%)	0	(0.000%)	
COMPLEX16         	777594		1	(0.000%)	0	(0.000%)	
```

`Testing DOUBLE PRECISION CS-Decomposition-routines-dcsd.out  CSD:     39 out of    600 tests failed to pass the threshold
 failing to pass the threshold: 39`
`Testing REAL              CS-Decomposition-routines-scsd.out  CSD:     12 out of    600 tests failed to pass the threshold
 failing to pass the threshold: 12
`

It used to be a single failure for `COMPLEX16`.

**Comment by martin-frbg** [comment] 2022-08-02 20:08
Still bisecting, but it looks like all was good on Jun 30 when 686 (cmake nagfor support) got merged, and the 12 errors in REAL (but nothing else yet) crept in by Jul 5

**Comment by martin-frbg** [comment] 2022-08-02 21:37
bisected the 12 errors in REAL to 
commit bdcd890a185482119c52dd7acd9a702f0cad782a
Author: Christoph Conrads <gitlab@christoph-conrads.name>
Date:   Mon Oct 25 18:42:55 2021 +0000

    SORCSD: fix documentation on matrix dimensions

 SRC/sorbdb2.f    | 4 ++--
 SRC/sorbdb4.f    | 2 +-
 SRC/sorcsd2by1.f | 2 +-
 3 files changed, 4 insertions(+), 4 deletions(-)

the date looks weird, but this is actually a small part of PR #647 which got merged on July 15 and the change in file
SRC/sorcsd2by1.f actually affected code rather than documentation. It seems likely that at least some of the errors in DOUBLE PRECISION may have been caused by related changes in that PR, but I have not verified that yet (close to midnight here)

**Comment by martin-frbg** [comment] 2022-08-03 07:08
Reverting
```
-           CALL SCOPY( M-P, WORK(IORBDB+P), 1, U2, 1 )
+           CALL SCOPY( M-Q, WORK(IORBDB+P), 1, U2, 1 )
```
in sorcsd2by1.f and copying back dorbdb6.f from the 3.10.1 release (sorry, no time to investigate the individual changes in that file today) makes all tests pass without error again. @christoph-conrads

**Comment by christoph-conrads** [comment] 2022-08-05 10:12
@langou ,

please revert my commits bdcd890a185482119c52dd7acd9a702f0cad782a and d245b4f6ef5ed18cff4ef53d75a96b49f259bc3a. They were piggy-backing onto PR #647 and should not have been part of this pull request.

I am sorry for the problems caused by these two unrelated commits.

**Comment by weslleyspereira** [comment] 2022-08-05 21:43
I reverted bdcd890 and d245b4f. See #697.

**Comment by langou** [comment] 2022-08-05 22:42
Thanks @weslleyspereira

**Closed** 2022-09-18 18:00 UTC
Labels: Type: Bug
