### ISSUE TITLE
Segmentation fault when running ./EIG/xeigtstz

### ISSUE THREAD

**Issue by xinye83** [Reference-LAPACK/lapack#354] opened 2019-09-20 04:37 UTC
I received the following warning messages when compiling 
```
ftn  -O2 -frecursive -c -o zhet21.o zhet21.f
zhet21.f:309:33:

zhet21.f:307:72:

             DO 20 J = 1, N - 1
                                                                        2
zhet21.f:309:33:

      $                     U( 1, J-1 ), 1, WORK, N )
                                 1
Warning: Array reference at (1) out of bounds (0 < 1) in loop beginning at (2)
```

```
ftn  -O2 -frecursive -c -o zhpt21.o zhpt21.f
zhpt21.f:328:33:

zhpt21.f:326:72:

             DO 20 J = 1, N - 1
                                                                        2
zhpt21.f:328:33:

      $                     U( 1, J-1 ), 1, WORK )
                                 1
Warning: Array reference at (1) out of bounds (0 < 1) in loop beginning at (2)
```

and segmentation fault at runtime
```
NEP: Testing Nonsymmetric Eigenvalue Problem routines
./EIG/xeigtstz < nep.in > znep.out 2>&1
/bin/sh: line 1: 17422 Segmentation fault      (core dumped) ./EIG/xeigtstz < nep.in > znep.out 2>&1
```

**Comment by martin-frbg** [comment] 2019-09-21 10:47
Duplicate of #333 and #335 - you need to run xeigtstz with a bigger stack size (or `ulimit -s unlimited`) to avoid the segfault from allocating a big array of test data on the stack.

**Closed** 2019-09-21 14:22 UTC

**Comment by cfshen1990** [comment] 2021-12-27 11:06
I also met this problem. The xeigtstz cannot be executed normally, with a result of "Segmentation fault (core dumped)". T he command "ulimit -s unlimited" cannot solve this problem.

**Comment by cfshen1990** [comment] 2021-12-27 11:07
> I received the following warning messages when compiling
> 
> ```
> ftn  -O2 -frecursive -c -o zhet21.o zhet21.f
> zhet21.f:309:33:
> 
> zhet21.f:307:72:
> 
>              DO 20 J = 1, N - 1
>                                                                         2
> zhet21.f:309:33:
> 
>       $                     U( 1, J-1 ), 1, WORK, N )
>                                  1
> Warning: Array reference at (1) out of bounds (0 < 1) in loop beginning at (2)
> ```
> 
> ```
> ftn  -O2 -frecursive -c -o zhpt21.o zhpt21.f
> zhpt21.f:328:33:
> 
> zhpt21.f:326:72:
> 
>              DO 20 J = 1, N - 1
>                                                                         2
> zhpt21.f:328:33:
> 
>       $                     U( 1, J-1 ), 1, WORK )
>                                  1
> Warning: Array reference at (1) out of bounds (0 < 1) in loop beginning at (2)
> ```
> 
> and segmentation fault at runtime
> 
> ```
> NEP: Testing Nonsymmetric Eigenvalue Problem routines
> ./EIG/xeigtstz < nep.in > znep.out 2>&1
> /bin/sh: line 1: 17422 Segmentation fault      (core dumped) ./EIG/xeigtstz < nep.in > znep.out 2>&1
> ```
I also met this problem. The xeigtstz cannot be executed normally, with a result of "Segmentation fault (core dumped)". T he command "ulimit -s unlimited" cannot solve this problem.

**Comment by martin-frbg** [comment] 2021-12-27 12:39
which version are you building ? the error in zhet21.f looks like what was fixed in response to #333 two years ago.

**Comment by cfshen1990** [comment] 2021-12-27 13:09
> which version are you building ? the error in zhet21.f looks like what was fixed in response to #333 two years ago.

lapack-3.9.0

**Comment by martin-frbg** [comment] 2021-12-27 14:02
current version (with the fixes for both problems mentioned here) is lapack-3.10.0
(If you really need to use 3.9.0, you can get the fix at https://github.com/Reference-LAPACK/lapack/pull/338.diff and apply it with the "patch" program)

**Comment by cfshen1990** [comment] 2021-12-27 15:35
> current version (with the fixes for both problems mentioned here) is lapack-3.10.0 (If you really need to use 3.9.0, you can get the fix at https://github.com/Reference-LAPACK/lapack/pull/338.diff and apply it with the "patch" program)

many thanks
