### ISSUE TITLE
There is no SPEVR

### ISSUE THREAD

**Issue by physkets** [Reference-LAPACK/lapack#245] opened 2018-03-10 04:35 UTC
I was looking through routines to solve the symmetric eigenvalue problem, and found two kinds of routines for regular matrices: SYEVX and SYEVR, but only one for packed matrices: SPEVX.

Is there any particular reason this is so? Also, most notes recommend the RRR routine. So then sould I un-pack my matrix and use SYEVR instead of SPEVX?

**Comment by langou** [comment] 2018-03-10 19:49
This question would be best suited on the forum: http://icl.cs.utk.edu/lapack-forum/
I answer anyway, but close the issue right away. Let us move to forum if we want to discuss more. 

We kind of stopped using/developing packed storage for symmetric matrices. The reason is that (1) you save half of storage, but storage is "cheap" now, (2) these routines are extremely slow (due to the storage format) and not suitable for hierarchical memories (caches), multicore, etc. So all in all, we stopped working and maintaining. MRRR is pretty recent (200x addition) and at that point we already gave up on packed storage. There was a new data structure (RFP=rectangular full packed) to store half  of a symmetric matrix, we worked on a few routines, performance were good, but half the storage might not be worth the effort any longer.

Julien.

**Closed by langou** 2018-03-10 19:49 UTC

**Comment by ilayn** [comment] 2018-03-11 00:23
@langou Does this comment extend to RFP format routines or not? We are trying to understand if we should expose RFP related routines in SciPy. If your comments extends to them too then we might not bother. Hence my question. Thanks in advance.

**Comment by physkets** [comment] 2018-03-11 15:07
@langou Thanks for explaining. In that case, I won't use packed routines in my code. I didn't know there was a forum!

**Comment by langou** [comment] 2018-03-11 16:00
Hi @ilayn, the discussion as far as RFP routines are concerned is bittersweet. RFP routines are good routines. (I wrote them!) But the trade-off here is (maintainability) vs (performance/storage gain). There are great routines: efficient and store half of the data. The problem is whether adding these routines into SciPy is maintainable on the long term. The RFP subroutines are in LAPACK now and we will not remove them. Julien.

**Comment by langou** [comment] 2018-03-11 16:01
@physkets 

> In that case, I won't use packed routines in my code.

Good idea.

> I didn't know there was a forum!

No worries.

**Comment by physkets** [comment] 2018-04-03 15:57
@langou I'm sorry to post an off-topic message, but I've attempted registering at the forum 10 or 20 times over a month, to be denied everytime by the message: "The submitted form was invalid. Try submitting again. The confirmation code you entered was incorrect."

I can't have made a mistake every single time. Is there an issue with the confirmation code?
