### ISSUE TITLE
Some of the examples get stuck in a loop when compiled with Intel Fortran 2017

### ISSUE THREAD

**Issue by ghost** [Reference-LAPACK/lapack#180] opened 2017-08-12 16:00 UTC
When compiled in release configuration Intel Fortran optimizes some code into infinite loops. Mostly from the source files like ssytri_3x.f chetri_3x.f zhetri2x.f; Some of the other ones reproduce problem as well when I was trying to code my own things. The debug build works fine.

The points where they get stuck can be seen below
![image](https://user-images.githubusercontent.com/17946402/29242154-1f1244f0-7f90-11e7-89bc-19e87b836d9b.png)
![image](https://user-images.githubusercontent.com/17946402/29242158-27e69022-7f90-11e7-81a0-713ab57621e2.png)

The build was made using command `cmake .. -G"NMake Makefiles JOM" -DCMAKE_INSTALL_PREFIX=C:\devel -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAPACKE=On`

**Comment by langou** [comment] 2017-08-12 23:23
Thanks @artej11. I forwarded to the Intel people.

**Comment by jeffhammond** [comment] 2017-08-15 03:42
@langou I won't be able to reproduce this because I don't use Windows but hopefully someone in the compiler support team can.

**Comment by jeffhammond** [comment] 2017-08-15 03:46
@artej11 Can you provide full details on the Windows version number (not just "Windows 10" but the distribution and perhaps also the build number), the Intel Fortran version (`ifort --version` on Linux/Mac but maybe `ifort /Qversion` or something like that on Windows), and your processor model number?  Thanks.

**Comment by jeffhammond** [comment] 2017-09-07 22:25
@artej11 Intel compiler support was able to reproduce this bug and it's in the internal bug tracking system.  Thanks for reporting it.

**Comment by artej11** [comment] 2017-09-08 12:54
Sorry, was away doing other project so couldn't provide any versions. On the other hand there are few more bugs I found when trying to compile my stuff on windows using the GNU libraries. For Intel people there is one more bug, if they have a public tracker or smth I could report it myself. Basically if you have multiple installation of VS community 2017 the intel c paralell studio installer will crash just before going into interface. The bug completely prevents uninstalling or modifying your Intel compilers installation. For example, if you have both the release and preview version(had to install preview because of VS2017 bug making it impossible to compile ceres-solver at all, which I reported and it is already fixed in preview).

**Comment by jeffhammond** [comment] 2017-09-08 13:50
http://support.intel.com is the Intel support website.  Please feel free to report issues directly.  You can mention issue 02999696 is related, since that is the one I reported already.  It will help them assign the ticket to someone who knows the history.

**Closed** 2023-06-01 16:45 UTC
